version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "postgres_awe"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=postgres_awe
      - PORT=5000
      - JWT_SECRET=some_secret_ket
      - JWT_EXPIRES=100000s
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app